/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
  CopyrightOutline,
  LockOutline,
  LogoutOutline,
  SettingOutline,
  UserOutline,
  CaretRightOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  CopyrightOutline,
  LockOutline,
  LogoutOutline,
  SettingOutline,
  UserOutline, 
  CaretRightOutline
];